name: content-review
description: "Quality check against brand voice and standards"
author: "Blog Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
date: system-generated

installed_path: "{project-root}/blog/workflows/content-review"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false

dependencies:
  - marketing  # Blog pack requires marketing pack agents

team:
  - derek-neighbors-author\n  - james-edit-content-editor (marketing pack)
