name: linkedin-response-formula
description: "Generate brand-aligned LinkedIn responses"
author: "Blog Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
date: system-generated

installed_path: "{project-root}/blog/workflows/linkedin-response-formula"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false

dependencies:
  - marketing  # Blog pack requires marketing pack agents

team:
  - derek-neighbors-author\n  - michael-linkedin-specialist (marketing pack)
