# Marketing Collaboration Workflow Configuration
# Created using BMB *create-workflow patterns

name: marketing-collab
description: "Create medically accurate marketing content with clinical validation"
author: "Medical Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/medical/config.yaml"
output_folder: "{config_source}:medical_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/medical/workflows/marketing-collab"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/marketing-collab-{date}.md"

team:
  medical_director:
    agent: "medical/agents/dr-michael-johnson"
    role: "Clinical accuracy and medical oversight"
  
  writer:
    agent: "medical/agents/maya-patel-medical-writer"
    role: "Medical content creation and plain language"

variables:
  content_type:
    prompt: "Marketing content type?"
    type: "single-select"
    required: true
    options:
      - "Website Copy"
      - "Product Messaging"
      - "Case Study"
      - "White Paper"
      - "Press Release"
      - "Sales Collateral"
      - "Social Media"
  
  target_audience:
    prompt: "Target audience?"
    type: "single-select"
    required: true
    options:
      - "Patients/Consumers"
      - "Healthcare Providers"
      - "Hospital Administrators"
      - "Payers/Health Plans"
      - "Investors"
  
  marketing_goal:
    prompt: "Marketing goal?"
    type: "text"
    required: true
    example: "Position product as leader in remote patient monitoring"
  
  clinical_claims:
    prompt: "Clinical claims to validate?"
    type: "text"
    required: true
    example: "Reduces readmissions by 30%, FDA-cleared"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

