name: marketing-collab
description: "Collaborate with marketing teams to create medically accurate, patient-centered marketing content"
author: "Medical Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/medical/workflows/marketing-collab"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/template.md"
output_file: "{output_folder}/marketing-content-{date}.md"

variables:
  content_brief: "" # Marketing brief with goals, audience, messaging
  content_type: "general" # general | product-launch | patient-education | provider-focused
  
team:
  - dr-michael-johnson # Medical Director - clinical validation
  - maya-patel # Medical Writer - content creation

recommended_inputs:
  - marketing_brief: "Target audience, messaging goals, brand guidelines"
  - product_info: "Feature details, clinical evidence, benefits"

