# Cover Image Prompt Workflow Configuration
# Created using BMB *create-workflow patterns

name: cover-image-prompt
description: "Generate visual prompt for blog cover image with brand guidelines"
author: "Blog Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/blog/config.yaml"
output_folder: "{config_source}:blog_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/blog/workflows/cover-image-prompt"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/cover-image-prompt-{date}.md"

team:
  author:
    agent: "blog/agents/derek-neighbors-author"
    role: "Visual concept and brand alignment"

variables:
  post_title:
    prompt: "Blog post title?"
    type: "text"
    required: true
  
  content_pillar:
    prompt: "Content pillar?"
    type: "text"
    required: true
  
  key_themes:
    prompt: "Key themes or concepts?"
    type: "text"
    required: true
  
  image_style:
    prompt: "Preferred image style?"
    type: "single-select"
    default: "abstract-conceptual"
    options:
      - "abstract-conceptual"
      - "photographic-real"
      - "minimalist-clean"
      - "bold-graphic"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

