# Provider Training Workflow Configuration
# Created using BMB *create-workflow patterns

name: provider-training
description: "Create medical training curriculum with assessments and learning outcomes"
author: "Medical Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/medical/config.yaml"
output_folder: "{config_source}:medical_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
specialty_focus: "{config_source}:specialty_focus"
date: system-generated

installed_path: "{project-root}/medical/workflows/provider-training"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/provider-training-{date}.md"

team:
  educator:
    agent: "medical/agents/dr-james-carter-educator"
    role: "Curriculum design and learning outcomes"
  
  nurse:
    agent: "medical/agents/nurse-brittany-hinsley"
    role: "Practical workflow validation"
  
  medical_director:
    agent: "medical/agents/dr-michael-johnson"
    role: "Clinical accuracy review"

variables:
  training_topic:
    prompt: "Training topic or system?"
    type: "text"
    required: true
  
  target_learners:
    prompt: "Who is being trained?"
    type: "multi-select"
    required: true
    options:
      - "Physicians"
      - "Nurses"
      - "Medical Assistants"
      - "Administrative Staff"
      - "Pharmacists"
      - "Other Clinical Staff"
  
  training_format:
    prompt: "Training delivery format?"
    type: "single-select"
    options:
      - "In-Person"
      - "Online/Self-Paced"
      - "Blended"
      - "Simulation-Based"
  
  duration:
    prompt: "Target training duration?"
    type: "single-select"
    options:
      - "< 30 minutes"
      - "30-60 minutes"
      - "1-2 hours"
      - "Half day"
      - "Full day"
      - "Multi-session"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

