name: provider-training
description: "Design healthcare provider training curriculum with learning objectives and assessments"
author: "Medical Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
installed_path: "{project-root}/medical/workflows/provider-training"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false
output_file: "{output_folder}/provider-training-{date}.md"

variables:
  training_topic: ""
  target_learners: "" # Physicians, nurses, medical students, etc.
  
team:
  - dr-james-carter
  - nurse-brittany-hinsley
  - dr-michael-johnson

