name: social-media-generation
description: "Create all social content from blog post"
author: "Blog Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
date: system-generated

installed_path: "{project-root}/blog/workflows/social-media-generation"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false

dependencies:
  - marketing  # Blog pack requires marketing pack agents

team:
  - derek-neighbors-author\n  - orion-blog-orchestrator\n  - alex-social-strategist (marketing pack)\n  - michael-linkedin-specialist (marketing pack)\n  - tyler-x-specialist (marketing pack)
