# Internal Linking Strategy Workflow Configuration
# Created using BMB *create-workflow patterns

name: internal-linking-strategy
description: "Add strategic internal links to blog post with anchor text recommendations"
author: "Blog Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/blog/config.yaml"
output_folder: "{config_source}:blog_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/blog/workflows/internal-linking-strategy"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/internal-links-{date}.md"

team:
  author:
    agent: "blog/agents/derek-neighbors-author"
    role: "Content context and linking strategy"

variables:
  blog_post:
    prompt: "Blog post content or URL?"
    type: "text"
    required: true
  
  site_content_inventory:
    prompt: "Link to content inventory or sitemap?"
    type: "text"
    required: false
  
  linking_goal:
    prompt: "Primary linking goal?"
    type: "single-select"
    default: "seo-authority"
    options:
      - "seo-authority"
      - "reader-journey"
      - "conversion-funnel"
      - "balanced"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

