name: ppc-campaign
description: "Launch paid advertising campaign"
author: "Marketing Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/marketing/workflows/ppc-campaign"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false
output_file: "{output_folder}/ppc-campaign-{date}.md"

variables:
  brief: ""
  
team:
  - rachel-ads-ppc\n  - chris-convert-cro\n  - priya-analytics-expert
