# Content Calendar Planning Workflow Configuration
# Created using BMB *create-workflow patterns

name: content-calendar-planning
description: "Plan 30-90 day editorial calendar with topics, keywords, and deadlines"
author: "Blog Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/blog/config.yaml"
output_folder: "{config_source}:blog_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/blog/workflows/content-calendar-planning"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/content-calendar-{date}.md"

team:
  author:
    agent: "blog/agents/derek-neighbors-author"
    role: "Content direction and pillar alignment"

variables:
  calendar_duration:
    prompt: "Planning timeframe?"
    type: "single-select"
    default: "90-days"
    options:
      - "30-days"
      - "90-days"
      - "quarterly"
  
  publishing_frequency:
    prompt: "Publishing frequency?"
    type: "single-select"
    default: "daily"
    options:
      - "daily"
      - "5x-week"
      - "3x-week"
      - "2x-week"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

