# HIPAA Audit Workflow Configuration
# Created using BMB *create-workflow patterns

name: hipaa-audit
description: "Conduct HIPAA compliance review with remediation recommendations"
author: "Medical Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/medical/config.yaml"
output_folder: "{config_source}:medical_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
hipaa_compliance_mode: "{config_source}:hipaa_compliance_mode"
date: system-generated

installed_path: "{project-root}/medical/workflows/hipaa-audit"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/hipaa-audit-{date}.md"

team:
  privacy:
    agent: "medical/agents/lisa-chang-privacy-officer"
    role: "HIPAA compliance and privacy analysis"

variables:
  audit_scope:
    prompt: "What to audit?"
    type: "single-select"
    required: true
    options:
      - "New Feature/Product"
      - "Data Flow/Integration"
      - "Access Controls"
      - "Full System Audit"
      - "Incident Response"
  
  feature_description:
    prompt: "Feature or system description?"
    type: "text"
    required: true
  
  phi_handling:
    prompt: "How is PHI handled?"
    type: "text"
    required: true
    example: "Stores patient names, DOB, diagnoses in PostgreSQL database"
  
  audit_focus:
    prompt: "Priority audit areas?"
    type: "multi-select"
    options:
      - "Administrative Safeguards"
      - "Physical Safeguards"
      - "Technical Safeguards"
      - "PHI Access Controls"
      - "Audit Trails"
      - "Encryption"
      - "Business Associate Agreements"
      - "Breach Notification"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

