# SEO Optimization Workflow Configuration
# Created using BMB *create-workflow patterns

name: seo-optimization
description: "Optimize blog post for search and AI discovery with meta, schema, and internal links"
author: "Blog Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/blog/config.yaml"
output_folder: "{config_source}:blog_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/blog/workflows/seo-optimization"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/seo-optimized-{date}.md"

team:
  author:
    agent: "blog/agents/derek-neighbors-author"
    role: "SEO strategy and content optimization"

variables:
  draft_post:
    prompt: "Draft blog post content or URL?"
    type: "text"
    required: true
  
  target_keywords:
    prompt: "Primary and secondary keywords?"
    type: "text"
    required: true
  
  optimization_priority:
    prompt: "SEO priority?"
    type: "single-select"
    default: "balanced"
    options:
      - "high-seo-focus"
      - "balanced"
      - "reader-first"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

