code: medical
name: "Medical Pack"
description: "Clinical expertise agents for healthcare SaaS teams — medical directors, nurses, pharmacists, HIPAA officers, and EHR specialists"
version: "0.1.0"
default_selected: false
dependencies:
  - bmm
  - bmb


