# Competitive Analysis Workflow Configuration
# Created using BMB *create-workflow patterns

name: competitive-analysis
description: "Analyze market positioning and competitors to identify opportunities and differentiation strategies"
author: "Marketing Pack Team"
workflow_type: "document"

# Configuration loading
config_source: "{project-root}/bmad/marketing/config.yaml"
output_folder: "{config_source}:marketing_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
company_industry: "{config_source}:company_industry"
target_audience: "{config_source}:target_audience"
date: system-generated

# Workflow paths
installed_path: "{project-root}/marketing/workflows/competitive-analysis"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
output_file: "{output_folder}/competitive-analysis-{date}.md"

# Team agents
team:
  strategist:
    agent: "marketing/agents/marcus-brand-strategist"
    role: "Positioning and differentiation strategy"
  
  analyst:
    agent: "marketing/agents/priya-analytics-expert"
    role: "Data analysis and market sizing"
  
  product:
    agent: "marketing/agents/natalie-product-marketing"
    role: "Product feature comparison"

# Input variables
variables:
  competitors_list:
    prompt: "List your main competitors (comma-separated)"
    type: "text"
    example: "CompanyA, CompanyB, CompanyC"
  
  analysis_focus:
    prompt: "What aspects to analyze?"
    type: "multi-select"
    options:
      - "Product Features"
      - "Pricing Strategy"
      - "Marketing Positioning"
      - "Target Audience"
      - "Distribution Channels"
      - "Content Strategy"
      - "Social Presence"
  
  market_segment:
    prompt: "Which market segment to focus on?"
    type: "text"
    example: "Mid-market B2B SaaS"
  
  analysis_depth:
    prompt: "Analysis depth?"
    type: "single-select"
    default: "standard"
    options:
      - "quick-overview"
      - "standard"
      - "comprehensive"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

