# Patient Content Workflow Configuration
# Created using BMB *create-workflow patterns

name: patient-content
description: "Create patient-facing education materials with plain language and medical accuracy"
author: "Medical Pack Team"
workflow_type: "document"

config_source: "{project-root}/bmad/medical/config.yaml"
output_folder: "{config_source}:medical_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/medical/workflows/patient-content"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
output_file: "{output_folder}/patient-content-{date}.md"

team:
  writer:
    agent: "medical/agents/maya-patel-medical-writer"
    role: "Plain language medical writing"
  
  validator:
    agent: "medical/agents/nurse-brittany-hinsley"
    role: "Clinical validation and patient perspective"

variables:
  content_topic:
    prompt: "What medical topic to explain?"
    type: "text"
    required: true
  
  target_audience:
    prompt: "Target audience?"
    type: "single-select"
    options:
      - "General Public"
      - "Patients (Specific Condition)"
      - "Caregivers"
      - "Pediatric Patients/Parents"
  
  reading_level:
    prompt: "Target reading level?"
    type: "single-select"
    default: "6th-8th-grade"
    options:
      - "4th-6th-grade"
      - "6th-8th-grade"
      - "high-school"
  
  content_length:
    prompt: "Content length?"
    type: "single-select"
    default: "500-750"
    options:
      - "250-500"
      - "500-750"
      - "750-1000"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

