# Marketing Pack Module Configuration
# This file defines installation questions and module configuration values

code: marketing
name: "Marketing Pack"
default_selected: false
description: "Complete AI marketing department for small teams - 31 specialists"
version: "1.0.0"
author: "Derek Neighbors"

prompt:
  - "Thank you for choosing Marketing Pack!"
  - "Your complete AI marketing department with 31 specialists across strategy, content, performance, social media, PR, and analytics."
  - "Perfect for small teams and startups that need enterprise-level marketing expertise."

# Core config values are automatically inherited:
## user_name
## communication_language
## document_output_language
## output_folder

# ============================================================================
# CONFIGURATION FIELDS
# ============================================================================

# Marketing output location
marketing_output_path:
  prompt: "Where should marketing pack save strategies, campaigns, and content?"
  default: "output/marketing"
  result: "{project-root}/{value}"

# Company industry/vertical
company_industry:
  prompt: "What industry are you in?"
  default: "SaaS / Software"
  result: "{value}"
  single-select:
    - "SaaS / Software"
    - "E-Commerce / Retail"
    - "Healthcare / MedTech"
    - "FinTech / Financial Services"
    - "Education / EdTech"
    - "Professional Services"
    - "Other"

# Marketing focus areas
marketing_focus:
  prompt: "What are your primary marketing focus areas? (select all that apply)"
  default: ["Demand Generation / Lead Gen"]
  result: "{value}"
  multi-select:
    - "Brand Awareness"
    - "Demand Generation / Lead Gen"
    - "Content Marketing"
    - "Social Media Growth"
    - "Performance Marketing / Paid Ads"
    - "Product Marketing"
    - "Community Building"

# Target audience
target_audience:
  prompt: "Who is your primary target audience?"
  default: "B2B - Business to Business"
  result: "{value}"
  single-select:
    - "B2B - Business to Business"
    - "B2C - Business to Consumer"
    - "B2B2C - Business to Business to Consumer (Hybrid)"
    - "D2C - Direct to Consumer"

# Marketing maturity level
marketing_maturity:
  prompt: "What's your current marketing maturity level?"
  default: "Growing - Have basics, need to scale"
  result: "{value}"
  single-select:
    - "Startup - Building from scratch"
    - "Growing - Have basics, need to scale"
    - "Established - Optimizing and scaling"
    - "Enterprise - Complex, multi-channel"

# Marketing disclaimer mode
include_marketing_disclaimers:
  prompt: "Include marketing best practice disclaimers?"
  default: "Yes - Include disclaimers about review and compliance"
  result: "{value}"
  single-select:
    - "Yes - Include disclaimers about review and compliance"
    - "No - Skip disclaimers"

# Data paths (static)
marketing_data_path:
  result: "{project-root}/bmad/marketing/data"

templates_path:
  result: "{project-root}/bmad/marketing/templates"

brand_assets_path:
  result: "{project-root}/bmad/marketing/data/brand-assets"

