name: clinical-review
description: "Multi-agent clinical review of product features, user stories, or design artifacts for patient safety, clinical accuracy, and regulatory compliance"
author: "Medical Pack Team"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/medical/workflows/clinical-review"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Template for clinical review report
template: "{installed_path}/template.md"
output_file: "{output_folder}/clinical-review-{date}.md"

# Variables
variables:
  artifact_path: "" # Path to feature spec, user story, or design doc to review
  review_focus: "comprehensive" # Options: comprehensive, safety-only, compliance-only, quick-scan
  
# Team agents for this workflow
team:
  - dr-michael-johnson # Medical Director - clinical strategy
  - nurse-brittany-hinsley # Patient Care - patient experience
  - ashley-rutledge # Paramedic - emergency scenarios
  - dr-alex-kim # Pharmacist - medication safety
  - lisa-chang # Privacy Officer - HIPAA/PHI compliance

# Recommended inputs
recommended_inputs:
  - artifact_to_review: "Feature spec, user story, PRD, or design document"
  - clinical_guidelines: "Relevant clinical guidelines or standards"

