name: video-script
description: "YouTube/TikTok video scripting"
author: "Marketing Pack Team"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/marketing/workflows/video-script"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false
output_file: "{output_folder}/video-script-{date}.md"

variables:
  brief: ""
  
team:
  - ryan-video-creator\n  - emma-words-copywriter\n  - zoe-tiktok-specialist
