# Video Script Workflow Configuration
# Created using BMB *create-workflow patterns

name: video-script
description: "Create YouTube or TikTok video script with hooks, B-roll notes, and CTAs"
author: "Marketing Pack Team"
workflow_type: "document"

# Configuration loading
config_source: "{project-root}/bmad/marketing/config.yaml"
output_folder: "{config_source}:marketing_output_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
company_industry: "{config_source}:company_industry"
target_audience: "{config_source}:target_audience"
date: system-generated

# Workflow paths
installed_path: "{project-root}/marketing/workflows/video-script"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
output_file: "{output_folder}/video-script-{date}.md"

# Team agents
team:
  video:
    agent: "marketing/agents/ryan-video-creator"
    role: "Video structure and production notes"
  
  writer:
    agent: "marketing/agents/emma-words-copywriter"
    role: "Script writing and messaging"
  
  tiktok:
    agent: "marketing/agents/zoe-tiktok-specialist"
    role: "Short-form optimization (if TikTok)"
    conditional: "platform == 'TikTok'"

# Input variables
variables:
  video_topic:
    prompt: "What is the video about?"
    type: "text"
    required: true
  
  target_platform:
    prompt: "Primary platform?"
    type: "single-select"
    required: true
    default: "YouTube"
    options:
      - "YouTube"
      - "TikTok"
      - "Instagram Reels"
      - "YouTube Shorts"
      - "LinkedIn Video"
  
  video_length:
    prompt: "Target video length?"
    type: "single-select"
    default: "5-8min"
    options:
      - "< 60 seconds"
      - "60-90 seconds"
      - "2-3 minutes"
      - "5-8 minutes"
      - "10-15 minutes"
      - "15+ minutes"
  
  video_style:
    prompt: "Video style/format?"
    type: "single-select"
    default: "talking-head"
    options:
      - "talking-head"
      - "screen-recording"
      - "b-roll-heavy"
      - "interview"
      - "documentary"
      - "vlog-style"
  
  hook_angle:
    prompt: "Hook/opening angle?"
    type: "text"
    example: "Pattern interrupt, question, bold statement"
  
  cta_goal:
    prompt: "Call-to-action goal?"
    type: "single-select"
    default: "subscribe"
    options:
      - "subscribe"
      - "visit-website"
      - "download-resource"
      - "comment-engage"
      - "product-trial"

metadata:
  created_by: "BMB *create-workflow"
  created_date: "2025-10-28"
  bmad_core_version: "6.0-alpha"
  workflow_version: "1.0.0"

